apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: servicebusapp
  name: servicebusapp
  namespace: servicebus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servicebusapp
  strategy: {}
  template:
    metadata:
      labels:
        app: servicebusapp
    spec:
      containers:
      - image: ghcr.io/levi106/servicebus-sample-web:main-ms
        name: servicebusapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: ai
              key: connectionstring
        - name: SPRING_JMS_SERVICEBUS_CONNECTION-STRING
          valueFrom:
            secretKeyRef:
              name: sb
              key: connectionstring
        - name: SPRING_JMS_SERVICEBUS_IDLE-TIMEOUT
          value: "60000"
        - name: SPRING_JMS_SERVICEBUS_PRICING-TIER
          value: "standard"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: servicebusapp
  name: servicebusapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: servicebusapp
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine
  name: alpine
spec:
  containers:
  - args:
    - sh
    - -c
    - 'apk --no-cache add curl; while true; do curl -X POST "10.0.44.93:8080/messages?message=hello";
      sleep 1; done; '
    image: alpine
    name: alpine
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
